### ISSUE TITLE
Terrain roughness length formula

### ISSUE THREAD

**Issue by neverfox** [sebwehrle/cleo#7]
https://github.com/sebwehrle/cleo/blob/c949d1657890d50915e7c7293a8ea187de6b0f53/cleo/assess.py#L174

Forgive me if I'm missing something, but this looks to be a rearrangement of the [wind power law](https://windroseexcel.com/guides/vertical-extrapolation-of-wind-speed/) solving for the wind shear exponent/coefficient, not roughness length, right? Wouldn't roughness length be a rearrangement of the wind log law? Or...

```python
terrain_roughness_length = np.exp((u_mean_100 * np.log(50) - u_mean_50 * np.log(100)) / (u_mean_100 - u_mean_50))
```

**Comment by sebwehrle** [comment]
yes, you’re right. thank you for pointing that out!

**Comment by sebwehrle** [comment]
Corrected naming to `wind_shear` / `wind_shear_coefficient`.
